name: gll
description: "Orgnization management application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+13

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Firebase - Let pubspec find the latest compatible versions
  firebase_core:
  firebase_database:
  firebase_storage:
  firebase_app_check:
  firebase_ui_firestore:

  # UI & Navigation
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  pinput: ^3.0.1
  flutter_svg: ^2.0.16
  shimmer: ^3.0.0
  dotted_border: ^2.0.0
  dropdown_search: ^6.0.2
  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.9.0
  # Networking & Data
  retrofit: ^4.4.1
  dio: ^5.7.0
  dio_http_formatter: ^3.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Utilities & Storage
  intl: ^0.20.1
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  path_provider: ^2.1.5
  file_picker: ^10.1.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  open_file: ^3.5.10
  connectivity_plus: ^6.0.1
  emailjs: ^4.0.0

  # Mapping
  flutter_map: ^8.1.1
  flutter_map_tile_caching: ^10.1.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  latlong2: ^0.9.1
  # PDF & Signature
  syncfusion_flutter_pdf: ^31.2.16
  syncfusion_flutter_pdfviewer: ^31.2.16
  flutter_pdfview: ^1.4.3
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  flutter_launcher_icons: ^0.14.3
  rename: ^3.1.0

  # Analysis & Linting
  flutter_lints: ^5.0.0
  timeago: ^3.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/welcome/
    - assets/more/
    - assets/resources/
    - assets/home/
    - assets/events/
    - assets/pdf/
    - assets/signatures/
    - assets/certificates/
    - assets/badges/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
